# GitHub Pages Configuration
title: "Advanced Software Modeling and Design - RL Project"
description: "A comprehensive exploration of Reinforcement Learning approaches from basic Q-Learning to Multi-Agent systems"

# Theme
theme: jekyll-theme-cayman

# GitHub Pages settings
baseurl: ""
url: ""

# Navigation
header_pages:
  - index.md
  - gridqlearning/README.md
  - visualqlearning/README.md
  - marl/README.md

plantuml:
  plantuml_jar: plantuml.jar # path to plantuml.jar
  type: utxt                         # type (passed as -t option, ex: -tutxt)
  extension: txt                     # output extension override
  plantuml_args: -nometadata         # extra args to be passed to plantuml
  java_args: -Xmx1G                  # extra args to be passed to java

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/